# Generated by Django 4.0.3 on 2023-09-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('confidence', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image_path', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('face_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imagelive.face')),
            ],
        ),
    ]
